## Numpy

In [56]:
np.__version__

'1.24.3'

In [2]:
import numpy as np

In [26]:
range(10)

range(0, 10)

In [27]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr=np.arange(6)
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
arr1=np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
arr11=arr1.reshape((3,3))
arr11

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr12=np.arange(10,19).reshape((3,3))
arr12

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [25]:
dot=np.dot(arr11,arr12)          # multiply two metrics 
dot

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [31]:
ayush=np.array(["yash","arya","raj"])
print(ayush)
print(type(ayush))
print(np.ndim(ayush))

['yash' 'arya' 'raj']
<class 'numpy.ndarray'>
1


In [33]:
abhi=ayush.copy()
abhi

array(['yash', 'arya', 'raj'], dtype='<U4')

In [34]:
ayush[2].itemsize

12

In [35]:
ayush.shape

(3,)

In [36]:
ayush.ndim

1

In [37]:
ayush.size

3

In [38]:
ayush.dtype

dtype('<U4')

In [19]:
import numpy as np
x=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(x)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr.shape

(3, 3)

In [24]:
arr.size

9

In [20]:
arr.ndim

2

In [21]:
arr.itemsize

4

In [25]:
arr.dtype

dtype('int32')

# Creation of Array

In [26]:
arr=np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [32]:
arr=np.ones((5,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [99]:
arr=np.ones((5,5),dtype=np.int64)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [39]:
arr=np.ones((5,5),dtype=np.int64)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [40]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [41]:
import numpy as np
a=np.array([1,2,3])
b=a.copy()
print(b)
a[0]=0
print(b)

[1 2 3]
[1 2 3]


In [42]:
np.full((3,3),5)      # change the number

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

# Arange

In [42]:
arr=np.arange(0,20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [43]:
arr=np.arange(0,20,2)  #(start, stop, steps)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


# Linspace

In [44]:
arr=np.linspace(0,20)
print(arr)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]


In [54]:
arr=np.linspace(0,20,5)  # (start, stop, number of element)
print(arr)

[ 0.  5. 10. 15. 20.]


In [57]:
std_marks=np.array([46,75,40])
total_marks=np.array([80,80,80])
std_marks/total_marks

array([0.575 , 0.9375, 0.5   ])

In [60]:
data=np.array([[1,2],[3,4],[5,6],[7,8]])
data

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [82]:
data[1,]             #indexing

array([3, 4])

In [79]:
data[0:4,[1]]        #slicing

array([[2],
       [4],
       [6],
       [8]])

In [83]:
data[2,1]

6