In [4]:
import numpy as np

### swapping rows of array

In [3]:
a=np.arange(25).reshape(5,5)
print("before swapping: ",a)
a[[0,1]]=a[[1,0]]
print("after swapping: ",a)

before swapping:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
after swapping:  [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [21]:
a[,[0,1]]=a[,[1,0]]
a

SyntaxError: invalid syntax (3449955188.py, line 1)

In [9]:
arr1=np.random.randint(0,100,5)
arr2=np.random.randint(0,100,5)

In [11]:
arr1


array([88, 24, 51, 36, 75])

In [12]:
arr2

array([50, 44,  9, 87, 75])

In [14]:
x=np.equal(arr1,arr2)
x

array([False, False, False, False,  True])

In [16]:
np.isreal(arr1)

array([ True,  True,  True,  True,  True])

In [18]:
np.iscomplex(arr2)

array([False, False, False, False, False])

In [19]:
np.greater(arr1,arr2)

array([ True, False,  True, False, False])

In [20]:
np.less(arr1,arr2)

array([False,  True, False,  True, False])