In [1]:
import numpy as np

In [17]:
x=[[1,2,3,4],[4,5,6,7],[7,8,9,3],[4,7,3,5]]
arr=np.array(x)
x

[[1, 2, 3, 4], [4, 5, 6, 7], [7, 8, 9, 3], [4, 7, 3, 5]]

In [6]:
arr.shape

(4, 4)

In [7]:
arr.reshape(2,8)

array([[1, 2, 3, 4, 4, 5, 6, 7],
       [7, 8, 9, 3, 4, 7, 3, 5]])

In [8]:
arr.reshape(8,2)

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7],
       [7, 8],
       [9, 3],
       [4, 7],
       [3, 5]])

In [15]:
np.vsplit(arr,4)

[array([[1, 2, 3, 4]]),
 array([[4, 5, 6, 7]]),
 array([[7, 8, 9, 3]]),
 array([[4, 7, 3, 5]])]

#### reshape method

In [21]:
arr.reshape(4,4)

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 3],
       [4, 7, 3, 5]])

In [23]:
are=np.reshape(arr,(4,4))
are

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 3],
       [4, 7, 3, 5]])

#### converting into 1 D array

In [24]:
arr.ravel()

array([1, 2, 3, 4, 4, 5, 6, 7, 7, 8, 9, 3, 4, 7, 3, 5])

In [26]:
arr.reshape(-1)

array([1, 2, 3, 4, 4, 5, 6, 7, 7, 8, 9, 3, 4, 7, 3, 5])

In [27]:
arr.flatten()

array([1, 2, 3, 4, 4, 5, 6, 7, 7, 8, 9, 3, 4, 7, 3, 5])

#### transpose 

In [28]:
arr

array([[1, 2, 3, 4],
       [4, 5, 6, 7],
       [7, 8, 9, 3],
       [4, 7, 3, 5]])

In [32]:
np.transpose(arr) # convert rows to column and column to rows

array([[1, 4, 7, 4],
       [2, 5, 8, 7],
       [3, 6, 9, 3],
       [4, 7, 3, 5]])

In [33]:
arr.T

array([[1, 4, 7, 4],
       [2, 5, 8, 7],
       [3, 6, 9, 3],
       [4, 7, 3, 5]])

In [34]:
arr.transpose()

array([[1, 4, 7, 4],
       [2, 5, 8, 7],
       [3, 6, 9, 3],
       [4, 7, 3, 5]])

#### expanding dimention of array

In [35]:
x=np.array([1,5])
print(x)
x.shape

[1 5]


(2,)

In [36]:
y=np.expand_dims(x,axis=0)
y.shape

(1, 2)

In [37]:
y

array([[1, 5]])

In [38]:
z=np.expand_dims(x,axis=1)
z.shape

(2, 1)

In [39]:
z

array([[1],
       [5]])

#### squeeze (removing a dimension)

In [40]:
x=np.array([[[0],[1],[2]]])
x.shape

(1, 3, 1)

In [42]:
a=np.squeeze(x,axis=0)
a.shape

(3, 1)

In [43]:
a

array([[0],
       [1],
       [2]])

In [45]:
a=np.squeeze(x,axis=2)
a.shape

(1, 3)

In [46]:
a

array([[0, 1, 2]])

#### concatenate array

In [50]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6]])
c=np.concatenate((a,b),axis=None)   # join in one dimension
c

array([1, 2, 3, 4, 5, 6])

In [51]:
c=np.concatenate((a,b),axis=0) # join in rows
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
c=np.concatenate((a,b.T),axis=1)  # join in coloumns
c

array([[1, 2, 5],
       [3, 4, 6]])

In [55]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.stack((a,b))              # join in rows and convert into 2d

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np.column_stack((a,b))      # join column

array([[1, 4],
       [2, 5],
       [3, 6]])

In [57]:
np.hstack((a,b))   # horizontally add

array([1, 2, 3, 4, 5, 6])

In [58]:
np.vstack((a,b))   # vertically add

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
x=np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [70]:
x,y,z=np.split(x,3)  # creating 3 array

In [71]:
x

array([0, 1, 2])

In [72]:
y

array([3, 4, 5])

In [73]:
z

array([6, 7, 8])

In [64]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
np.hsplit(a,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
np.vsplit(a,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]